import type { Athlete } from "@/components/AthleteCard";


// 24 homens
  
export const athletes: Athlete[] = [
  {
    slug: "Tunde",
    name: "Tunde",
    position: "SG",
    nationality: "Portugal",
    team: "BARREIRENSE",
    available: true,
    gender: "men",
    photo: "/athletes/Tunde.png",
  },
  {
    slug: "Diego",
    name: "Diego",
    position: "SG",
    nationality: "Espanha",
    team: "Lisboa BC",
    available: true,
    gender: "men",
    photo: "/athletes/Diego_v1.png",
  },
  {
    slug: "Antonio-Monteiro",
    name: "Antonio Monteiro",
    position: "SG",
    nationality: "Portugal",
    team: "Lisboa BC",
    available: true,
    gender: "men",
    photo: "/athletes/antonio_v1.png",
  },
  {
    slug: "Angelo",
    name: "Angelo",
    position: "SG",
    nationality: "Portugal",
    team: "Lisboa BC",
    available: true,
    gender: "men",
    photo: "/athletes/angelo_v1.png",
  },

  {
    slug: "Arnette",
    name: "Arnette Hallman",
    position: "SG",
    nationality: "Portugal",
    team: "Lisboa BC",
    available: true,
    gender: "men",
    photo: "/athletes/arnette_v1.png",
  },
  {
    slug: "Balderas",
    name: "Balderas",
    position: "SG",
    nationality: "Portugal",
    team: "Lisboa BC",
    available: true,
    gender: "men",
    photo: "/athletes/balderas.png",
  },

  {
    slug: "Darnell",
    name: "Darnell",
    position: "SG",
    nationality: "Portugal",
    team: "Lisboa BC",
    available: true,
    gender: "men",
    photo: "/athletes/darnell.webp",
  },

  {
    slug: "Diogo",
    name: "Diogo Gameiro",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/Diogo.png",
  },
  {
    slug: "Eneko",
    name: "Eneko",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/eneko.png",
  },

  {
    slug: "fabio",
    name: "Fabio Lima",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/fabio.png",
  },

  {
    slug: "inigo",
    name: "Inigo",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/Inigo.png",
  },
  {
    slug: "jaques",
    name: "Jaques Conceição",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/jaques.png",
  },
  {
    slug: "pablo",
    name: "Pablo",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/pablo_v2.jpg",
  },
  {
    slug: "salvador",
    name: "Salvador Gomes",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/salvador.png",
  },
  {
    slug: "unai",
    name: "Unai",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/unai.png",
  },
  {
    slug: "andre",
    name: "Andre",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/webp-_4.png",
  },
  {
    slug: "jose",
    name: "Jose Barbosa",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/ze png.png",
  },
  {
    slug: "ze",
    name: "Ze silva",
    position: "SG",
    nationality: "Portugal",
    team: "SLBenfica",
    available: true,
    gender: "men",
    photo: "/athletes/ze_v2.png",
  },

  /* woman */

  {
    slug: "ainho",
    name: "Ainhoa",
    position: "PG",
    nationality: "Portugal",
    team: "Benfica Women",
    available: true,
    gender: "women",
    photo: "/athletes/AINHOA_V1.png",
  },
  {
    slug: "Joana",
    name: "Joana Soeiro",
    position: "SF",
    nationality: "Spain",
    team: "SLBENFICA",
    available: true,
    gender: "women",
    photo: "/athletes/joana_sl.png",
  },

  {
    slug: "uxia",
    name: "Uxia",
    position: "SF",
    nationality: "Spain",
    team: "SLBENFICA",
    available: true,
    gender: "women",
    photo: "/athletes/uxia.png",
  },
  {
    slug: "Rafa",
    name: "Rapha Monteiro",
    position: "SF",
    nationality: "Spain",
    team: "Melilla",
    available: true,
    gender: "women",
    photo: "/athletes/rapha png.png",
  },
  {
    slug: "eva",
    name: "Eva",
    position: "SF",
    nationality: "Spain",
    team: "SLBENFICA",
    available: true,
    gender: "women",
    photo: "/athletes/eva_v2.png",
  },
  {
    slug: "gara",
    name: "Gara",
    position: "SF",
    nationality: "Spain",
    team: "SLBENFICA",
    available: true,
    gender: "women",
    photo: "/athletes/gara_v2.png",
  },
  {
    slug: "joana",
    name: "Joana Monteiro",
    position: "SF",
    nationality: "Spain",
    team: "SLBENFICA",
    available: true,
    gender: "women",
    photo: "/athletes/joana antonio.png",
  },
  {
    slug: "margarida",
    name: "Margarida",
    position: "SF",
    nationality: "Spain",
    team: "SLBENFICA",
    available: true,
    gender: "women",
    photo: "/athletes/Margarida_v2.png",
  },
  {
    slug: "Mari",
    name: "Mariana",
    position: "SF",
    nationality: "Spain",
    team: "SLBENFICA",
    available: true,
    gender: "women",
    photo: "/athletes/MARIANA.png",
  },
  {
    slug: "sabina",
    name: "Sabina",
    position: "SF",
    nationality: "Spain",
    team: "SLBENFICA",
    available: true,
    gender: "women",
    photo: "/athletes/sabina.png",
  },
  {
    slug: "sofia",
    name: "Sofia",
    position: "SF",
    nationality: "Spain",
    team: "SLBENFICA",
    available: true,
    gender: "women",
    photo: "/athletes/Sofia_v1.webp",
  },
];




export const media = [
  {
    slug: "highlight-01",
    type: "highlight",
    title: "Highlights — Game Week",
    date: "2026-02-12",
    platform: "YouTube",
  },
  {
    slug: "interview-01",
    type: "interview",
    title: "Interview — Athlete Story",
    date: "2026-02-05",
    platform: "YouTube",
  },
  {
    slug: "highlight-02",
    type: "highlight",
    title: "Top Plays — Season",
    date: "2026-01-28",
    platform: "YouTube",
  },
  {
    slug: "training-01",
    type: "training",
    title: "Training Session — Behind the Scenes",
    date: "2026-01-20",
    platform: "Instagram",
  },
];

export const news = [
  {
    slug: "agency-launch",
    title: "Orange Ball Dreams Official Launch",
    date: "2026-02-10",
    excerpt: "The agency platform is now live.",
  },
];

